//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AUCapture_WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AUCapture_WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die cancel ähnelt.
        /// </summary>
        public static string CancelText {
            get {
                return ResourceManager.GetString("CancelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoMuteUs ähnelt.
        /// </summary>
        public static string ConnectionStatus_AUTOMUTEUS {
            get {
                return ResourceManager.GetString("ConnectionStatus.AUTOMUTEUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die User Bot ähnelt.
        /// </summary>
        public static string ConnectionStatus_USER_BOT {
            get {
                return ResourceManager.GetString("ConnectionStatus.USER BOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game code ähnelt.
        /// </summary>
        public static string GameCodeTooltip {
            get {
                return ResourceManager.GetString("GameCodeTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Game code ähnelt.
        /// </summary>
        public static string GameCodeWatermark {
            get {
                return ResourceManager.GetString("GameCodeWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die DISCUSSION ähnelt.
        /// </summary>
        public static string GameState_DISCUSSION {
            get {
                return ResourceManager.GetString("GameState.DISCUSSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ENDED ähnelt.
        /// </summary>
        public static string GameState_ENDED {
            get {
                return ResourceManager.GetString("GameState.ENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die LOBBY ähnelt.
        /// </summary>
        public static string GameState_LOBBY {
            get {
                return ResourceManager.GetString("GameState.LOBBY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die MENU ähnelt.
        /// </summary>
        public static string GameState_MENU {
            get {
                return ResourceManager.GetString("GameState.MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die TASKS ähnelt.
        /// </summary>
        public static string GameState_TASKS {
            get {
                return ResourceManager.GetString("GameState.TASKS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die UNKNOWN ähnelt.
        /// </summary>
        public static string GameState_UNKNOWN {
            get {
                return ResourceManager.GetString("GameState.UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current status ähnelt.
        /// </summary>
        public static string GameStateTooltip {
            get {
                return ResourceManager.GetString("GameStateTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Code:  ähnelt.
        /// </summary>
        public static string ManualConnectionCode {
            get {
                return ResourceManager.GetString("ManualConnectionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manual Connection ähnelt.
        /// </summary>
        public static string ManualConnectionHeader {
            get {
                return ResourceManager.GetString("ManualConnectionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Host:  ähnelt.
        /// </summary>
        public static string ManualConnectionHost {
            get {
                return ResourceManager.GetString("ManualConnectionHost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string ManualConnectionSubmitButton {
            get {
                return ResourceManager.GetString("ManualConnectionSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the manual connection window ähnelt.
        /// </summary>
        public static string ManualConnectTooltip {
            get {
                return ResourceManager.GetString("ManualConnectTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Current map ähnelt.
        /// </summary>
        public static string MapTooltip {
            get {
                return ResourceManager.GetString("MapTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Map ähnelt.
        /// </summary>
        public static string MapWatermark {
            get {
                return ResourceManager.GetString("MapWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Off ähnelt.
        /// </summary>
        public static string OffText {
            get {
                return ResourceManager.GetString("OffText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die On ähnelt.
        /// </summary>
        public static string OnText {
            get {
                return ResourceManager.GetString("OnText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Get AutoMuteUs premium ähnelt.
        /// </summary>
        public static string PremiumTooltip {
            get {
                return ResourceManager.GetString("PremiumTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We detected an update to {0}, But there is no public key in this capture so we will not be able to verify integrity. Please download the latest release off the github page. ähnelt.
        /// </summary>
        public static string PrivateKeyErrorMessage {
            get {
                return ResourceManager.GetString("PrivateKeyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AutoUpdater failed ähnelt.
        /// </summary>
        public static string PrivateKeyErrorTitle {
            get {
                return ResourceManager.GetString("PrivateKeyErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die retry ähnelt.
        /// </summary>
        public static string RetryText {
            get {
                return ResourceManager.GetString("RetryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die App version: ähnelt.
        /// </summary>
        public static string SettingsAboutTabAppVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabAppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auto updater ähnelt.
        /// </summary>
        public static string SettingsAboutTabAutoUpdaterHeader {
            get {
                return ResourceManager.GetString("SettingsAboutTabAutoUpdaterHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Contributors:  ähnelt.
        /// </summary>
        public static string SettingsAboutTabContributorsButton {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Show contributors ähnelt.
        /// </summary>
        public static string SettingsAboutTabContributorsButtonToolTip {
            get {
                return ResourceManager.GetString("SettingsAboutTabContributorsButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die About ähnelt.
        /// </summary>
        public static string SettingsAboutTabHeader {
            get {
                return ResourceManager.GetString("SettingsAboutTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Latest version: ähnelt.
        /// </summary>
        public static string SettingsAboutTabLatestVersion {
            get {
                return ResourceManager.GetString("SettingsAboutTabLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open log folder ähnelt.
        /// </summary>
        public static string SettingsDebugOpenLogsFolderButton {
            get {
                return ResourceManager.GetString("SettingsDebugOpenLogsFolderButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug mode ähnelt.
        /// </summary>
        public static string SettingsDebugTabDebugModeSwitch {
            get {
                return ResourceManager.GetString("SettingsDebugTabDebugModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Debug ähnelt.
        /// </summary>
        public static string SettingsDebugTabHeader {
            get {
                return ResourceManager.GetString("SettingsDebugTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reload offsets ähnelt.
        /// </summary>
        public static string SettingsDebugTabReloadOffsetsButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabReloadOffsetsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Reset Config ähnelt.
        /// </summary>
        public static string SettingsDebugTabResetConfigButton {
            get {
                return ResourceManager.GetString("SettingsDebugTabResetConfigButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Discord ähnelt.
        /// </summary>
        public static string SettingsDiscordTabHeader {
            get {
                return ResourceManager.GetString("SettingsDiscordTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Submit ähnelt.
        /// </summary>
        public static string SettingsDiscordTabSubmitButton {
            get {
                return ResourceManager.GetString("SettingsDiscordTabSubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Paste token here ähnelt.
        /// </summary>
        public static string SettingsDiscordTabTokenWatermark {
            get {
                return ResourceManager.GetString("SettingsDiscordTabTokenWatermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always copy game code ähnelt.
        /// </summary>
        public static string SettingsGeneralTabAlwaysCopyGameCode {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysCopyGameCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Always on top ähnelt.
        /// </summary>
        public static string SettingsGeneralTabAlwaysOnTop {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAlwaysOnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die API Server ähnelt.
        /// </summary>
        public static string SettingsGeneralTabAPIServer {
            get {
                return ResourceManager.GetString("SettingsGeneralTabAPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Focus window on connect ähnelt.
        /// </summary>
        public static string SettingsGeneralTabFocusOnConnect {
            get {
                return ResourceManager.GetString("SettingsGeneralTabFocusOnConnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die General ähnelt.
        /// </summary>
        public static string SettingsGeneralTabHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language ähnelt.
        /// </summary>
        public static string SettingsGeneralTabLanguageHeader {
            get {
                return ResourceManager.GetString("SettingsGeneralTabLanguageHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Startup memes ähnelt.
        /// </summary>
        public static string SettingsGeneralTabStartupMemes {
            get {
                return ResourceManager.GetString("SettingsGeneralTabStartupMemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Settings ähnelt.
        /// </summary>
        public static string SettingsHeader {
            get {
                return ResourceManager.GetString("SettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open the settings window ähnelt.
        /// </summary>
        public static string SettingsTooltip {
            get {
                return ResourceManager.GetString("SettingsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AUCapture-TOR ähnelt.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No thanks ähnelt.
        /// </summary>
        public static string UpdateNotificationDecline {
            get {
                return ResourceManager.GetString("UpdateNotificationDecline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Caution ähnelt.
        /// </summary>
        public static string UpdateNotificationHeader {
            get {
                return ResourceManager.GetString("UpdateNotificationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die We&apos;ve detected you&apos;re using an older version of AmongUsCapture!
        ///Your version: {0}
        ///Latest version: {1} ähnelt.
        /// </summary>
        public static string UpdateNotificationMessage {
            get {
                return ResourceManager.GetString("UpdateNotificationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update ähnelt.
        /// </summary>
        public static string UpdateNotificationUpdate {
            get {
                return ResourceManager.GetString("UpdateNotificationUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for Among Us ähnelt.
        /// </summary>
        public static string WaitingForAmongUs {
            get {
                return ResourceManager.GetString("WaitingForAmongUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waiting for Lobby ähnelt.
        /// </summary>
        public static string WaitingForLobby {
            get {
                return ResourceManager.GetString("WaitingForLobby", resourceCulture);
            }
        }
    }
}
